modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"

[[mods]]
modId="ecologics"
version="1.1.3"
displayName="Ecologics"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ecologics"
logoFile="logo.png"
authors="Designed and coded by SameButDifferent. Artwork by Foquito Azul, Avila, and Drig."
description='''
Improves the vanilla biomes.
'''

[[dependencies.ecologics]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.5,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ecologics]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ecologics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
