modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="ecologics"
version="1.5.5"
displayName="Ecologics"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ecologics"
logoFile="logo.png"
authors="Designed and coded by SameButDifferent. Artwork by Foquito Azul, Avila, Drig, and Crispytwig."
description='''
Improves the vanilla biomes.
'''

[[dependencies.ecologics]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ecologics]]
    modId="decorative_blocks"
    mandatory=false
    versionRange="[2.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ecologics]]
    modId="farmersdelight"
    mandatory=false
    versionRange="[1.18.2-1.0.4,]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ecologics]]
    modId="mcwbridges"
    mandatory=false
    versionRange="[2.0.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ecologics]]
    modId="quark"
    mandatory=false
    versionRange="[2.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ecologics]]
    modId="autoreglib"
    mandatory=false
    versionRange="[1.7,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ecologics]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ecologics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
